### ISSUE TITLE
412 Precondition Failed

### ISSUE THREAD

**Issue by neversay** [dpjanes/homestar-wemo#4]
I run the "homestar runner" for a hour, and found the on/off buttons on /things page does not work if it run longer than 10 minutes, I found some log like this:

{"name":"iotdb-upnp","module":"upnp/upnp-service","hostname":"anna","pid":4374,"level":50,"method":"UpnpService._resubscribe","sid":"uuid:1fd3638e-1dd2-11b2-ace6-cbce70195b53","buf":"<html><body><h1>412 Precondition Failed</h1></body></html>","statusCode":412,"msg":"problem with re-subscription","time":"2015-03-31T05:33:33.108Z","v":0}

{"name":"iotdb-upnp","module":"upnp/upnp-service","hostname":"anna","pid":4374,"level":50,"method":"Subscription._resubscribe","sid":"uuid:1fd3638e-1dd2-11b2-ace6-cbce70195b53","err":{},"buf":"<html><body><h1>412 Precondition Failed</h1></body></html>","cause":"UPnP protocol error or network problems","msg":"error resubscribing","time":"2015-03-31T05:33:33.110Z","v":0}

I guess the resubscribe might failed after it forgot the device.
Here is some log from my raspberry pi:
https://gist.github.com/neversay/ebf732a9294451b92940

**Comment by dpjanes** [comment]
when it rediscovers the WeMo, the old Bridge is still reporting that it can
reach the WeMo, so it ignores it. Working on fix.

**Comment by dpjanes** [comment]
Fix pushed - there were several errors. You may have to do

npm update iotdb
npm update iotdb-upnp
npm update iotdb-wemo

I'm hoping nothing horrible happens because of peerdepenencies (you may
have to remove old versions if they do)

**Comment by neversay** [comment]
I tried and still no luck, the wemo lost control several minutes later.
Here is my versions:
iotdb: 0.5.12
iotdb-upnp: 0.0.8
iotdb-wemo: 0.0.12

It became "thing not found".

**Comment by neversay** [comment]
Here is new log file:
https://gist.github.com/neversay/322e3896498db8ab5300

**Comment by dpjanes** [comment]
Writing software is way harder than they tell you lol. At it, now on a
Raspberry Pi. I very much appreciate all you've done BTW, just in case I
haven't mentioned that.

**Comment by dpjanes** [comment]
The current issue is that homestar runner (which is installed with sudo &&
-g) runs iotdb under it's own node_modules rather than the node_modules in
the current directory.

I've changed runner.js now so it actually runs Node again rather than
requiring within it's own self, so it should see your locally installed
software.

Note that if it disconnects, it should rediscover within 30-90 seconds
depending on how the stars align.

I've been running this locally on my own Raspberry Pi (B+ I believe)
without issue

D.

**Comment by dpjanes** [comment]
To update

sudo npm update -g homestar

**Comment by dpjanes** [comment]
Are you still running the other upnp controller on the same device?

**Comment by neversay** [comment]
No. The R PI2 is running LMS and homestar only, and it is working fine now :)
